management.health.mongodb.enabled=false

spring.application.name=mobileproject-backend

spring.mongodb.uri=mongodb+srv://mobile_db_user:mobilePasswd@mobileapp-database.ifxslyb.mongodb.net/mobile_app_db?retryWrites=true&w=majority&appName=MobileApp-Database
spring.data.redis.url=${REDIS_URL:rediss://default:gQAAAAAAASR2AAIncDE0OTRiODQyMzgwYWE0MmQ1YTA3MjdmNGI0M2E1YTNiMnAxNzQ4NzA@in-bobcat-74870.upstash.io:6379}
spring.data.redis.repositories.enabled=false