services:
  - type: web
    name: mobileproject-backend
    runtime: docker
    region: singapore
    plan: free
    rootDir: mobileproject-backend
    healthCheckPath: /actuator/health
    dockerContext: mobileproject-backend
    dockerfilePath: mobileproject-backend/Dockerfile
    envVars:
      - key: APP_AUTH_TOKEN_SECRET
        generateValue: true
      - key: SEPAY_API_KEY
        sync: false
      - key: SEPAY_WEBHOOK_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SEPAY_TRANSFER_PREFIX
        value: YMW
