package com.mobileproject.mobileprojectbackend.auth.dto;

public record CoupleStatusResponse(
        boolean success,
        String message,
        boolean profileCompleted,
        boolean paired,
        String partnerUsername,
        String myCoupleCode,
        String myCoupleCodeExpiresAt,
        String incomingRequestId,
        String incomingRequesterUsername,
        String incomingRequesterDisplayName,
        String incomingCreatedAt,
        String outgoingRequestId,
        String outgoingRecipientUsername,
        String outgoingStatus,
        String outgoingUpdatedAt,
        String coupleId,
        String startAt,
        Long daysTogether,
        Boolean anniversaryTomorrow
) {
    public static CoupleStatusResponse success(String message,
                                               boolean profileCompleted,
                                               boolean paired,
                                               String partnerUsername,
                                               String myCoupleCode,
                                               String myCoupleCodeExpiresAt,
                                               String incomingRequestId,
                                               String incomingRequesterUsername,
                                               String incomingRequesterDisplayName,
                                               String incomingCreatedAt,
                                               String outgoingRequestId,
                                               String outgoingRecipientUsername,
                                               String outgoingStatus,
                                               String outgoingUpdatedAt,
                                               String coupleId,
                                               String startAt,
                                               Long daysTogether,
                                               Boolean anniversaryTomorrow) {
        return new CoupleStatusResponse(
                true,
                message,
                profileCompleted,
                paired,
                partnerUsername,
                myCoupleCode,
                myCoupleCodeExpiresAt,
                incomingRequestId,
                incomingRequesterUsername,
                incomingRequesterDisplayName,
                incomingCreatedAt,
                outgoingRequestId,
                outgoingRecipientUsername,
                outgoingStatus,
                outgoingUpdatedAt,
                coupleId,
                startAt,
                daysTogether,
                anniversaryTomorrow
        );
    }
}
