package com.example.mobileproject.presentation.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal val MobileProjectLightColorScheme = lightColorScheme(
    primary = Color(0xFFBA1A4B),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E1),
    onPrimaryContainer = Color(0xFF3F0015),
    secondary = Color(0xFF535E7A),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDAE2FF),
    onSecondaryContainer = Color(0xFF1A243F),
    tertiary = Color(0xFF7A2943),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD9E1),
    onTertiaryContainer = Color(0xFF3F0015),
    background = Color(0xFFFFFBFA),
    onBackground = Color(0xFF201A1B),
    surface = Color(0xFFFFFBFA),
    onSurface = Color(0xFF201A1B),
    surfaceVariant = Color(0xFFF3DFE2),
    onSurfaceVariant = Color(0xFF524346),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFFFF0F2),
    surfaceContainer = Color(0xFFFFE8EC),
    surfaceContainerHigh = Color(0xFFFFDDE3),
    surfaceContainerHighest = Color(0xFFF5D3D9),
    inverseSurface = Color(0xFF362F30),
    inverseOnSurface = Color(0xFFFBEEEE),
    inversePrimary = Color(0xFFFFB2C3),
    outline = Color(0xFF837375),
    outlineVariant = Color(0xFFD7C1C5),
    scrim = Color(0xFF000000),
    error = Color(0xFFB3261E),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFF9DEDC),
    onErrorContainer = Color(0xFF410E0B),
)

internal val MobileProjectDarkColorScheme = darkColorScheme(
    primary = Color(0xFFFFB2C3),
    onPrimary = Color(0xFF670025),
    primaryContainer = Color(0xFF900037),
    onPrimaryContainer = Color(0xFFFFD9E1),
    secondary = Color(0xFFBBC6EA),
    onSecondary = Color(0xFF23304A),
    secondaryContainer = Color(0xFF3B4661),
    onSecondaryContainer = Color(0xFFDAE2FF),
    tertiary = Color(0xFFD08AA0),
    onTertiary = Color(0xFF3F0015),
    tertiaryContainer = Color(0xFF5D1F35),
    onTertiaryContainer = Color(0xFFFFD9E1),
    background = Color(0xFF1A1113),
    onBackground = Color(0xFFECE0E0),
    surface = Color(0xFF1A1113),
    onSurface = Color(0xFFECE0E0),
    surfaceVariant = Color(0xFF524346),
    onSurfaceVariant = Color(0xFFD7C1C5),
    surfaceContainerLowest = Color(0xFF140C0E),
    surfaceContainerLow = Color(0xFF22191B),
    surfaceContainer = Color(0xFF271D1F),
    surfaceContainerHigh = Color(0xFF31272A),
    surfaceContainerHighest = Color(0xFF3D3234),
    inverseSurface = Color(0xFFECE0E0),
    inverseOnSurface = Color(0xFF362F30),
    inversePrimary = Color(0xFFBA1A4B),
    outline = Color(0xFF9D8C8F),
    outlineVariant = Color(0xFF524346),
    scrim = Color(0xFF000000),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
)
